apiVersion: github.coop.no/v1alpha1
kind: RepositoryConfig
metadata:
  name: github-workflow-approve-and-merge-dependabot-pr
spec:
  description: "No description provided"
  visibility: "public"


  branches:
    default: "main"
    protection:
      - id: "main"
        pattern: "main"
        requireSignedCommits: false
        requiredStatusChecks:
          checks:
            - "build"
        requiredPullRequestReviews:
          requireCodeOwnerReviews: true

